name: the-other-stuff
on:
  workflow_run:
    workflows:
      - stuff
    types: 
      - completed
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "github.sha ${{ github.sha }}"