name: the-other-stuff
on:
  workflow_run:
    workflows:
      - stuff
      - always-failing
    branches:
      - main
    types: 
      - completed
jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "github.sha ${{ github.sha }}"