name: the-other-stuff
on:
  push:
jobs:
  another-ci-again:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          #check-name: test # name of the existing check - omit to wait for all checks
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          #running-workflow-name: 'ci'
          check-name: ci
      - run: echo "github.sha ${{ github.sha }}"